channels:
 - defaults
 - anaconda
 - conda-forge
dependencies:
 - python=3.8.0
 - pip
 - pip:
   - azureml-mlflow==1.53.0
   - azure-ai-ml==1.11.0
   - pyarrow==11.0.0
   - scikit-learn==0.24.2
   - pandas==1.3.5
   - joblib==1.2.0
   - matplotlib==3.5.3
   - numpy==1.21.6
   - scipy==1.7.3
   - azureml-inference-server-http
   # Substitua estas linhas pelas versões específicas dos pacotes, se disponíveis
   - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-client
   - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-collector